config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tasks#index"

  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update', as: :task_update
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :select_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def select_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v6.1.2/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title, class: "form-label" %>
  <%= f.text_field :title, class: "form-control mb-3" %>
  <%= f.label :details, class: "form-label" %>
  <%= f.text_field :details, class: "form-control mb-3" %>
  <% if @task.persisted? %>
    <%= f.label :completed, class: "form-label" %>
    <%= f.check_box :completed, class: "form-check-input mb-3" %>
  <% end %>
  <div>
    <%= f.submit class: "btn btn-primary mb-3" %>
    <button class="btn btn-light border border-secondary-subtle mb-3">
      <%= link_to "Cancel", tasks_path %>
    </button>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="wrapper">
  <div class="w-50">
    <h1>Edit task</h1>
    <div>
      <%= render "form", task: @task %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="wrapper">
  <div class="border border-secondary w-50 p-3">
    <h1 class="text-center">My Tasks</h1>
    <ul class="list-group my-3">
      <% @tasks.each do |task| %>
        <li class="list-group-item">
          <input type="checkbox"
            <%= "checked" if task.completed %>
            disabled
          >
          <%= link_to task.title, task_path(task) %>
          <%= link_to task_path(task),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-regular fa-trash-can"></i>
          <% end %>
        </li>
      <% end %>
    </ul>

    <button class="btn btn-warning border border-secondary-subtle"><%= link_to "Add a new task", tasks_new_path %></button>
  </div>
</div>

<%# task_path(task): the task refers to the specific task in the each-do loop %>
<%# Read up on how to put html inside link_to %>

app/views/tasks/new.html.erb
<div class="wrapper">
  <div class="w-50">
    <h1>Add new task</h1>
    <div>
      <%= render "form", task: @task %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="wrapper">
  <div class="w-50 border border-secondary p-3">
    <h1><%= @task.title %></h1>
    <p class="bg-light border border-secondary-subtle rounded p-3"><%= @task.details %></p>
    <div class="<%= @task.completed ? "bg-success bg-opacity-25 p-3" : "bg-danger bg-opacity-25 p-3" %>" >
      <input type="checkbox"
        <%= "checked" if @task.completed %>
        class="form-check-input"
        id="task-checkbox"
        disabled
      >
      <label class="form-check-label" for="task-checkbox">
        <%= @task.completed ? "This task is completed" : "This task is not completed" %>
      </label>
    </div>


    <div class="my-3">
      <button class="btn btn-warning border border-secondary-subtle"><%= link_to "Edit this task", task_edit_path %></button>
      <button class="btn btn-light border border-secondary-subtle"><%= link_to "Back to list", tasks_path %></button>
    </div>
  </div>
</div>